dist: trusty
sudo: required
language: java
jdk:
  - openjdk8
services:
  - docker
install:
# - ./mvnw -Ddocker.push.username=${DOCKER_USERNAME} -Ddocker.push.password=${DOCKER_PASSWORD} clean package
- docker version; docker info; env