apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    component: dns-controller-skydns
  name: dns-controller-skydns
  namespace: kube-system
spec:
  replicas: 1
  template:
    metadata:
      labels:
        component: dns-controller-skydns
      annotations:
        scheduler.alpha.kubernetes.io/critical-pod: ''
    spec:
      containers:
      - name: dns-controller-skydns
        image: quay.io/ferdi/k8s-dns-sky:1.0.0-SNAPSHOT
        resources:
          requests:
            cpu: 200m
            memory: 250Mi
          limits:
            memory: 350Mi
        imagePullPolicy: Always
        ports:
        - containerPort: 8080
        args:
        - --etcd.endpoints=https://192.168.1.2:23790
        - --etcd.ca-file=/etc/secrets/etcd-ca.crt
        - --etcd.cert-file=/etc/secrets/etcd-client.crt
        - --etcd.key-file=/etc/secrets/etcd-client.key
        livenessProbe:
          httpGet:
            path: /actuator/health
            port: 8080
            scheme: HTTP
          initialDelaySeconds: 60
          periodSeconds: 60
          timeoutSeconds: 20
          successThreshold: 1
          failureThreshold: 5
        readinessProbe:
          httpGet:
            path: /actuator/info
            port: 8080
            scheme: HTTP
          initialDelaySeconds: 15
          periodSeconds: 30
          timeoutSeconds: 20
        volumeMounts:
        - name: secrets
          mountPath: /etc/secrets
          readOnly: true
      volumes:
      - name: secrets
        secret:
          secretName: skydns-etcd-secret

